# Initialization

In [1]:
import logging

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
%matplotlib inline
%config InlineBackend.figure_format = 'png'
%config InlineBackend.figure_format = 'retina'

# Загрузка данных

In [3]:
items = pd.read_parquet("items.parquet")
events = pd.read_parquet("events.parquet")

# Разбиение с учётом хронологии

Рекомендательные системы на практике работают с учётом хронологии. Поэтому поток событий для тренировки и валидации полезно делить на то, что уже случилось, и что ещё случится. Это позволяет проводить валидацию на тех же пользователях, на которых тренировались, но на их событиях в будущем.

In [4]:
# зададим точку разбиения
train_test_global_time_split_date = pd.to_datetime("2017-08-01").date()
train_test_global_time_split_idx = events["started_at"] < train_test_global_time_split_date

events_train = events[train_test_global_time_split_idx]
events_test = events[~train_test_global_time_split_idx]

# количество пользователей в train и test
users_train = events_train["user_id"].drop_duplicates()
users_test = events_test["user_id"].drop_duplicates()
# количество пользователей, которые есть и в train, и в test
common_users = users_train[users_train.isin(users_test)]

print(len(users_train), len(users_test), len(common_users))

428220 123223 120858

# === Знакомство: "холодный" старт

In [13]:
cold_users = users_test[~users_test.isin(users_train)]

print(len(cold_users))

2365

In [14]:
from sklearn.preprocessing import MinMaxScaler

top_pop_start_date = pd.to_datetime("2015-01-01").date()

item_popularity = events_train \
    .query("started_at >= @top_pop_start_date") \
    .groupby(["item_id"]).agg(users=("user_id", "nunique"), avg_rating=("rating", "mean")).reset_index()

# нормализация пользователей и среднего рейтинга, требуется для их приведения к одному масштабу
scaler = MinMaxScaler()
item_popularity[["users_norm", "avg_rating_norm"]] = scaler.fit_transform(
    item_popularity[["users", "avg_rating"]]
)

# вычисляем popularity_score, как скор популярности со штрафом за низкий рейтинг
item_popularity["popularity_score"] = (
    item_popularity["users_norm"] * item_popularity["avg_rating_norm"]
)

# сортируем по убыванию popularity_score
item_popularity = item_popularity.sort_values(by='popularity_score', ascending=False)

# выбираем первые 100 айтемов со средней оценкой avg_rating не меньше 4
top_k_pop_items = item_popularity[:100]

In [15]:
top_k_pop_items

,item_id,users,avg_rating,users_norm,avg_rating_norm,popularity_score
35011,22557272,40690,3.788965,1.000000,0.697241,0.697241
37701,29056083,25785,3.801784,0.633685,0.700446,0.443862
32387,18007564,20207,4.321275,0.496596,0.830319,0.412333
32623,18143977,19462,4.290669,0.478287,0.822667,0.393471
2,3,15139,4.706057,0.372042,0.926514,0.344702
...,...,...,...,...,...,...
32073,17802724,6202,3.811996,0.152400,0.702999,0.107137
37008,26074181,6344,3.727932,0.155890,0.681983,0.106314
35980,23848559,5592,4.065629,0.137408,0.766407,0.105311
26024,10025305,4900,4.491224,0.120401,0.872806,0.105087
25134,8755785,4933,4.461788,0.121212,0.865447,0.104903

In [23]:
# добавляем информацию о книгах
top_k_pop_items = top_k_pop_items.merge(
    items.set_index("item_id")[["author", "title", "genre_and_votes", "publication_year"]], on="item_id")

with pd.option_context('display.max_rows', 100):
    display(top_k_pop_items[["item_id", "author", "title", "publication_year", "users", "avg_rating", "popularity_score", "genre_and_votes"]])

,item_id,author,title,publication_year,users,avg_rating,popularity_score,genre_and_votes
0,22557272,Paula Hawkins,The Girl on the Train,2015,40690,3.788965,0.697241,"{'Fiction': 9793, 'Mystery': 9190, 'Thriller':..."
1,29056083,"John Tiffany, Jack Thorne, J.K. Rowling",Harry Potter and the Cursed Child - Parts One ...,2016,25785,3.801784,0.443862,"{'Fantasy': 14466, 'Fiction': 4232, 'Young Adu..."
2,18007564,Andy Weir,The Martian,2014,20207,4.321275,0.412333,"{'Science Fiction': 11966, 'Fiction': 8430}"
3,18143977,Anthony Doerr,All the Light We Cannot See,2014,19462,4.290669,0.393471,"{'Historical-Historical Fiction': 13679, 'Fict..."
4,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Sorcerer's Stone (Harry P...,1997,15139,4.706057,0.344702,"{'Fantasy': 59818, 'Fiction': 17918, 'Young Ad..."
5,16096824,Sarah J. Maas,A Court of Thorns and Roses (A Court of Thorns...,2015,16770,4.301014,0.340108,"{'Fantasy': 14326, 'Young Adult': 4662, 'Roman..."
6,15881,"J.K. Rowling, Mary GrandPré",Harry Potter and the Chamber of Secrets (Harry...,1999,13043,4.632447,0.291076,"{'Fantasy': 50130, 'Young Adult': 15202, 'Fict..."
7,38447,Margaret Atwood,The Handmaid's Tale,1998,14611,4.232770,0.290194,"{'Fiction': 15424, 'Classics': 9937, 'Science ..."
8,9460487,Ransom Riggs,Miss Peregrine’s Home for Peculiar Children (M...,2008,16564,3.809949,0.285957,"{'Fantasy': 12454, 'Young Adult': 9293, 'Ficti..."
9,11235712,Marissa Meyer,"Cinder (The Lunar Chronicles, #1)",2012,14348,4.179189,0.280247,"{'Young Adult': 10539, 'Fantasy': 9237, 'Scien..."
10,17927395,Sarah J. Maas,A Court of Mist and Fury (A Court of Thorns an...,2016,12177,4.730640,0.279094,"{'Fantasy': 10186, 'Romance': 3346, 'Young Adu..."
11,5,"J.K. Rowling, Mary GrandPré",Harry Potter and the Prisoner of Azkaban (Harr...,2004,11890,4.770143,0.275401,"{'Fantasy': 49784, 'Young Adult': 15393, 'Fict..."
12,13206900,Marissa Meyer,"Winter (The Lunar Chronicles, #4)",2015,12291,4.534293,0.266881,"{'Fantasy': 4835, 'Young Adult': 4672, 'Scienc..."
13,21853621,Kristin Hannah,The Nightingale,2015,12294,4.528144,0.266482,"{'Historical-Historical Fiction': 10105, 'Fict..."
14,18692431,"Nicola Yoon, David Yoon","Everything, Everything",2015,14121,4.071454,0.266466,"{'Young Adult': 5175, 'Romance': 3234, 'Contem..."
15,6,"J.K. Rowling, Mary GrandPré",Harry Potter and the Goblet of Fire (Harry Pot...,2002,10679,4.764772,0.246997,"{'Fantasy': 48257, 'Young Adult': 15483, 'Fict..."
16,16068905,Rainbow Rowell,Fangirl,2013,12642,4.119839,0.242313,"{'Young Adult': 9301, 'Contemporary': 5760, 'R..."
17,23437156,Leigh Bardugo,"Six of Crows (Six of Crows, #1)",2015,11138,4.512300,0.240338,"{'Fantasy': 15409, 'Young Adult': 6520}"
18,9969571,Ernest Cline,Ready Player One,2011,11812,4.290044,0.238754,"{'Science Fiction': 10560, 'Fiction': 7713, 'Y..."
19,17167166,Sarah J. Maas,"Crown of Midnight (Throne of Glass, #2)",2013,11025,4.509751,0.237727,"{'Fantasy': 11344, 'Young Adult': 4695, 'Roman..."
20,15745753,Rainbow Rowell,Eleanor & Park,2013,12410,4.046575,0.232280,"{'Young Adult': 11593, 'Romance': 6881, 'Conte..."
21,13206760,Marissa Meyer,"Scarlet (The Lunar Chronicles, #2)",2013,11514,4.262376,0.230773,"{'Young Adult': 6930, 'Fantasy': 6267, 'Scienc..."
22,13206828,Marissa Meyer,"Cress (The Lunar Chronicles, #3)",2014,10605,4.487977,0.227251,"{'Young Adult': 5813, 'Fantasy': 5413, 'Scienc..."
23,18006496,Sarah J. Maas,"Queen of Shadows (Throne of Glass, #4)",2015,10241,4.610097,0.227134,"{'Fantasy': 8435, 'Young Adult': 3170, 'Romanc..."
24,20613470,Sarah J. Maas,"Heir of Fire (Throne of Glass, #3)",2014,10133,4.495608,0.217611,"{'Fantasy': 9677, 'Young Adult': 3800, 'Romanc..."
25,2657,Harper Lee,To Kill a Mockingbird,2006,10188,4.459069,0.216505,"{'Classics': 41773, 'Fiction': 21733, 'Histori..."
26,2,"J.K. Rowling, Mary GrandPré",Harry Potter and the Order of the Phoenix (Har...,2004,9528,4.685873,0.215754,"{'Fantasy': 46485, 'Young Adult': 15194, 'Fict..."
27,18774964,"Fredrik Backman, Henning Koch",A Man Called Ove,2014,10024,4.394852,0.209065,"{'Fiction': 7091, 'Contemporary': 1656, 'Audio..."
28,18460392,Jennifer Niven,All the Bright Places,2015,10870,4.122355,0.208514,"{'Young Adult': 4691, 'Contemporary': 2534, 'R..."
29,7896527,Sarah J. Maas,"Throne of Glass (Throne of Glass, #1)",2012,10329,4.219866,0.204323,"{'Fantasy': 16888, 'Young Adult': 7306, 'Roman..."
30,1,J.K. Rowling,Harry Potter and the Half-Blood Prince (Harry ...,2006,8728,4.796059,0.203545,"{'Fantasy': 46400, 'Young Adult': 15083, 'Fict..."
31,20170404,Emily St. John Mandel,Station Eleven,2014,10511,4.127961,0.201989,"{'Fiction': 5860, 'Science Fiction': 3274, 'Sc..."
32,136251,J.K. Rowling,Harry Potter and the Deathly Hallows (Harry Po...,2007,8390,4.850775,0.198482,"{'Fantasy': 46667, 'Young Adult': 15403, 'Fict..."
33,16143347,E. Lockhart,We Were Liars,2014,11023,3.781729,0.188381,"{'Young Adult': 7184, 'Contemporary': 3277, 'M..."
34,20910157,Amy Poehler,Yes Please,2014,10559,3.823563,0.183165,"{'Nonfiction': 6011, 'Autobiography-Memoir': 3..."
35,22328546,Victoria Aveyard,"Red Queen (Red Queen, #1)",2015,10001,3.980402,0.183121,"{'Fantasy': 10750, 'Young Adult': 6597, 'Scien..."
36,6442769,John Green,Paper Towns,2009,11206,3.609941,0.179682,"{'Young Adult': 9929, 'Contemporary': 3821, 'F..."
37,16101128,Rick Yancey,"The 5th Wave (The 5th Wave, #1)",2013,9383,4.035809,0.174998,"{'Young Adult': 5331, 'Science Fiction': 3197,..."
38,5470,"George Orwell, Erich Fromm",1984,1950,9059,4.124738,0.173904,"{'Classics': 33441, 'Fiction': 21086, 'Science..."
39,19063,Markus Zusak,The Book Thief,2008,8085,4.479530,0.172826,"{'Historical-Historical Fiction': 18340, 'Fict..."
40,23395680,"Amie Kaufman, Jay Kristoff","Illuminae (The Illuminae Files, #1)",2015,8170,4.380416,0.169669,"{'Science Fiction': 3927, 'Young Adult': 3535,..."
41,25494343,Cassandra Clare,"Lady Midnight (The Dark Artifices, #1)",2016,7717,4.558248,0.168691,"{'Fantasy': 4277, 'Young Adult': 2491, 'Romanc..."
42,22055262,V.E. Schwab,"A Darker Shade of Magic (Shades of Magic, #1)",2015,8660,4.138684,0.166985,"{'Fantasy': 14539, 'Young Adult': 2101, 'Ficti..."
43,10507293,Kiera Cass,"The Selection (The Selection, #1)",2012,8868,3.983536,0.162544,"{'Young Adult': 7810, 'Romance': 5841, 'Scienc..."
44,28260587,Sarah J. Maas,"Empire of Storms (Throne of Glass, #5)",2016,7416,4.557174,0.162061,"{'Fantasy': 6616, 'Young Adult': 2251, 'Romanc..."
45,23766634,Sarah J. Maas,A Court of Wings and Ruin (A Court of Thorns a...,2017,7455,4.490677,0.159868,"{'Fantasy': 7960, 'Romance': 2365, 'Young Adul..."
46,18798983,Renée Ahdieh,The Wrath and the Dawn (The Wrath and the Dawn...,2015,7887,4.255610,0.157744,"{'Fantasy': 5942, 'Young Adult': 3448, 'Romanc..."
47,27362503,Colleen Hoover,It Ends with Us,2008,7268,4.523115,0.157306,"{'Romance': 3077, 'Contemporary': 1673, 'New A..."
48,23174274,Victoria Aveyard,"Glass Sword (Red Queen, #2)",2016,8810,3.845062,0.153986,"{'Fantasy': 4595, 'Young Adult': 2873, 'Scienc..."
49,17675462,Maggie Stiefvater,"The Raven Boys (The Raven Cycle, #1)",2012,8049,4.096658,0.153124,"{'Fantasy': 9481, 'Young Adult': 7067, 'Fantas..."
50,23513349,Rupi Kaur,Milk and Honey,2014,7720,4.161788,0.149954,"{'Poetry': 14490, 'Feminism': 1105, 'Nonfictio..."
51,24817626,Harper Lee,Go Set a Watchman,2015,10116,3.313464,0.143778,"{'Fiction': 4306, 'Historical-Historical Ficti..."
52,9361589,Erin Morgenstern,The Night Circus,2011,7361,4.085858,0.139546,"{'Fantasy': 16749, 'Fiction': 7058, 'Romance':..."
53,256683,Cassandra Clare,"City of Bones (The Mortal Instruments, #1)",2007,7566,3.989823,0.138969,"{'Fantasy': 17924, 'Young Adult': 13460, 'Fant..."
54,22918050,Kiera Cass,"The Heir (The Selection, #4)",2015,8295,3.719470,0.138583,"{'Young Adult': 2668, 'Romance': 2119, 'Scienc..."
55,18635016,Kiera Cass,"The One (The Selection, #3)",2014,7340,4.073025,0.138569,"{'Young Adult': 4782, 'Romance': 3852, 'Scienc..."
56,15749186,Jenny Han,To All the Boys I've Loved Before (To All the ...,2015,7189,4.070942,0.135626,"{'Young Adult': 5919, 'Romance': 4965, 'Contem..."
57,22489107,Marissa Meyer,"Fairest (The Lunar Chronicles, #3.5)",2015,7254,4.040805,0.135509,"{'Fantasy': 2825, 'Young Adult': 2772, 'Scienc..."
58,10964,Diana Gabaldon,"Outlander (Outlander, #1)",2005,7002,4.126107,0.134470,"{'Historical-Historical Fiction': 10725, 'Roma..."
59,16248068,Kiera Cass,"The Elite (The Selection, #2)",2013,7873,3.778102,0.134368,"{'Young Adult': 5414, 'Romance': 4192, 'Scienc..."
60,10194157,Leigh Bardugo,"Shadow and Bone (The Grisha, #1)",2012,7120,4.058567,0.133783,"{'Fantasy': 14290, 'Young Adult': 6921, 'Roman..."
61,20698530,Jenny Han,P.S. I Still Love You (To All the Boys I've Lo...,2015,6918,4.109858,0.132166,"{'Young Adult': 3659, 'Romance': 3112, 'Contem..."
62,27833670,Blake Crouch,Dark Matter,2016,6747,4.121980,0.129402,"{'Science Fiction': 4244, 'Fiction': 3079, 'Th..."
63,22544764,Naomi Novik,Uprooted,2015,6728,4.107164,0.128425,"{'Fantasy': 13419, 'Young Adult': 2048, 'Ficti..."
64,28187,Rick Riordan,The Lightning Thief (Percy Jackson and the Oly...,2006,6445,4.208534,0.127036,"{'Fantasy': 21419, 'Young Adult': 9587, 'Fanta..."
65,15783514,Neil Gaiman,The Ocean at the End of the Lane,2013,6871,3.989812,0.126201,"{'Fantasy': 15115, 'Fiction': 6563, 'Horror': ..."
66,17235026,M.R. Carey,The Girl with All the Gifts,2014,6898,3.929255,0.124131,"{'Horror': 3542, 'Fiction': 2271, 'Science Fic..."
67,23164983,Ransom Riggs,Hollow City (Miss Peregrine’s Peculiar Childre...,2008,6639,4.041723,0.124057,"{'Fantasy': 4427, 'Young Adult': 3025, 'Fictio..."
68,15839976,Pierce Brown,"Red Rising (Red Rising, #1)",2014,6399,4.150180,0.123835,"{'Science Fiction': 4634, 'Fantasy': 2920, 'Yo..."
69,25489625,Ta-Nehisi Coates,Between the World and Me,2015,5762,4.470149,0.122831,"{'Nonfiction': 6587, 'Autobiography-Memoir': 2..."
70,32075671,Angie Thomas,The Hate U Give,2017,5385,4.707335,0.122639,"{'Young Adult': 8354, 'Fiction': 5014, 'Contem..."
71,5886881,Gillian Flynn,Dark Places,2009,6965,3.856281,0.122215,"{'Mystery': 4534, 'Fiction': 4055, 'Thriller':..."
72,28763485,Nicola Yoon,The Sun Is Also a Star,2016,6221,4.194663,0.122090,"{'Young Adult': 3806, 'Romance': 2512, 'Contem..."
73,22738563,Chimamanda Ngozi Adichie,We Should All Be Feminists,2014,5555,4.568317,0.121768,"{'Nonfiction': 6864, 'Feminism': 4519, 'Writin..."
74,26893819,Emma Cline,The Girls,2016,7854,3.513751,0.121289,"{'Fiction': 2494, 'Historical-Historical Ficti..."
75,99561,John Green,Looking for Alaska,2006,7010,3.801712,0.120654,"{'Young Adult': 12128, 'Fiction': 4626, 'Conte..."
76,13496,George R.R. Martin,"A Game of Thrones (A Song of Ice and Fire, #1)",2005,5699,4.440779,0.120460,"{'Fantasy': 44086, 'Fiction': 10111, 'Fantasy-..."
77,25111004,Colleen Hoover,November 9,2015,5806,4.366345,0.120067,"{'Romance': 1811, 'New Adult': 1296, 'Contempo..."
78,12262741,Cheryl Strayed,Wild: From Lost to Found on the Pacific Crest ...,2012,6550,3.958931,0.119062,"{'Nonfiction': 6335, 'Autobiography-Memoir': 4..."
79,7171637,Cassandra Clare,"Clockwork Angel (The Infernal Devices, #1)",2010,5869,4.261714,0.117598,"{'Fantasy': 10151, 'Young Adult': 7424, 'Fanta..."
80,1885,"Jane Austen, Anna Quindlen",Pride and Prejudice,2000,5700,4.316316,0.116123,"{'Classics': 46807, 'Fiction': 14324, 'Romance..."
81,23453112,"Aziz Ansari, Eric Klinenberg",Modern Romance,2015,6660,3.833784,0.115941,"{'Nonfiction': 4246, 'Humor': 1393, 'Audiobook..."
82,7613,"George Orwell, Boris Grabnar, Peter Škerl",Animal Farm,2003,5908,4.189235,0.115749,"{'Classics': 30122, 'Fiction': 17416, 'Science..."
83,186074,Patrick Rothfuss,The Name of the Wind (The Kingkiller Chronicle...,2007,5530,4.406510,0.115723,"{'Fantasy': 28188, 'Fiction': 4251, 'Fantasy-E..."
84,4671,"F. Scott Fitzgerald, Francis Scott Fitzgerald",The Great Gatsby,2004,6421,3.913253,0.114915,"{'Classics': 42010, 'Fiction': 19710, 'Academi..."
85,1582996,Cassandra Clare,"City of Ashes (The Mortal Instruments, #2)",2008,6050,4.083140,0.114588,"{'Fantasy': 11997, 'Young Adult': 9281, 'Fanta..."
86,18693763,Celeste Ng,Everything I Never Told You,2014,6528,3.854779,0.114485,"{'Fiction': 4803, 'Contemporary': 1263, 'Myste..."
87,13335037,Veronica Roth,"Divergent (Divergent, #1)",2012,5929,4.130882,0.114035,"{'Young Adult': 20260, 'Science Fiction-Dystop..."
88,28187230,Ruth Ware,The Woman in Cabin 10,2016,7040,3.626989,0.113614,"{'Mystery': 3384, 'Fiction': 2053, 'Thriller':..."
89,3777732,Cassandra Clare,"City of Glass (The Mortal Instruments, #3)",2008,5469,4.365332,0.113063,"{'Fantasy': 11194, 'Young Adult': 8549, 'Fanta..."
90,30555488,Colson Whitehead,The Underground Railroad,2016,6050,4.029752,0.112604,"{'Historical-Historical Fiction': 5191, 'Ficti..."
91,11870085,John Green,The Fault in Our Stars,2012,5819,4.130091,0.111891,"{'Young Adult': 20449, 'Fiction': 10338, 'Roma..."
92,15704307,"Brian K. Vaughan, Fiona Staples","Saga, Vol. 1 (Saga, #1)",2012,5322,4.410936,0.111514,"{'Sequential Art-Graphic Novels': 7803, 'Seque..."
93,16181775,Graeme Simsion,"The Rosie Project (Don Tillman, #1)",2013,6062,3.964698,0.110405,"{'Fiction': 5264, 'Romance': 3372, 'Contempora..."
94,17378508,Maggie Stiefvater,"Blue Lily, Lily Blue (The Raven Cycle, #3)",2014,5284,4.335541,0.108270,"{'Fantasy': 5121, 'Young Adult': 3651, 'Fantas..."
95,17802724,Liane Moriarty,The Husband's Secret,2013,6202,3.811996,0.107137,"{'Fiction': 3655, 'Mystery': 1344, 'Womens Fic..."
96,26074181,Kiera Cass,"The Crown (The Selection, #5)",2016,6344,3.727932,0.106314,"{'Young Adult': 1887, 'Romance': 1543, 'Scienc..."
97,23848559,Jenny Lawson,Furiously Happy: A Funny Book About Horrible T...,2015,5592,4.065629,0.105311,"{'Nonfiction': 3138, 'Humor': 1914, 'Autobiogr..."
98,10025305,Cassandra Clare,"Clockwork Prince (The Infernal Devices, #2)",2011,4900,4.491224,0.105087,"{'Fantasy': 7212, 'Young Adult': 5170, 'Romanc..."
99,8755785,Cassandra Clare,"City of Heavenly Fire (The Mortal Instruments,...",2014,4933,4.461788,0.104903,"{'Fantasy': 5999, 'Young Adult': 4162, 'Fantas..."

In [25]:
cold_users_events_with_recs = \
    events_test[events_test["user_id"].isin(cold_users)] \
    .merge(top_k_pop_items, on="item_id", how="left")

cold_user_items_no_avg_rating_idx = cold_users_events_with_recs["avg_rating"].isnull()
cold_user_recs = cold_users_events_with_recs[~cold_user_items_no_avg_rating_idx] \
    [["user_id", "item_id", "rating", "avg_rating"]]

In [ ]:
cold_user_recs

      user_id   item_id  rating  avg_rating
5     1338996  16096824       5    4.301014
8     1338996  18692431       5    4.071454
9     1338996  28763485       2    4.194663
15    1276025     38447       5    4.232770
21    1342439  17235026       4    3.929255
...       ...       ...     ...         ...
9656  1002425  17675462       5    4.096658
9659  1102243     10964       5    4.126107
9664  1195880   9969571       5    4.290044
9665  1195880   9361589       4    4.085858
9669  1253160  16181775       3    3.964698

[2091 rows x 4 columns]

In [29]:
len(cold_user_recs) / len(cold_users_events_with_recs)

0.2161910669975186

In [30]:
# посчитаем метрики рекомендаций
from sklearn.metrics import mean_squared_error, mean_absolute_error

rmse = mean_squared_error(cold_user_recs["rating"], cold_user_recs["avg_rating"], squared=False)
mae = mean_absolute_error(cold_user_recs["rating"], cold_user_recs["avg_rating"])
print(round(rmse, 2), round(mae, 2))

0.82 0.65

In [32]:
# посчитаем покрытие холодных пользователей рекомендациями

cold_users_hit_ratio = cold_users_events_with_recs.groupby("user_id").agg(hits=("avg_rating", lambda x: (~x.isnull()).mean()))

print(f"Доля пользователей без релевантных рекомендаций: {(cold_users_hit_ratio == 0).mean().iat[0]:.2f}")
print(f"Среднее покрытие пользователей: {cold_users_hit_ratio[cold_users_hit_ratio != 0].mean().iat[0]:.2f}")

Доля пользователей без релевантных рекомендаций: 0.57
Среднее покрытие пользователей: 0.46

# === Знакомство: первые персональные рекомендации

In [5]:
from scipy.sparse import coo_matrix

events_pivot = events.copy()

events_pivot["user_code"] = events_pivot["user_id"].astype("category").cat.codes
events_pivot["item_code"] = events_pivot["item_id"].astype("category").cat.codes

ui_matrix = coo_matrix(
    (events_pivot["rating"], (events_pivot["user_code"], events_pivot["item_code"]))
).tocsr()

In [6]:
ui_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11751086 stored elements and shape (430585, 41673)>

In [9]:
100 - (11751086 / (430585 * 41673) * 100)

99.93451160571009

In [11]:
from surprise import Dataset, Reader
from surprise import SVD

# используем Reader из библиотеки surprise для преобразования событий (events)
# в формат, необходимый surprise
reader = Reader(rating_scale=(1, 5))
surprise_train_set = Dataset.load_from_df(events_train[['user_id', 'item_id', 'rating']], reader)
surprise_train_set = surprise_train_set.build_full_trainset()

# инициализируем модель
svd_model = SVD(n_factors=100, random_state=0)

# обучаем модель
svd_model.fit(surprise_train_set)

In [12]:
surprise_test_set = list(events_test[['user_id', 'item_id', 'rating']].itertuples(index=False))

# получаем рекомендации для тестовой выборки
svd_predictions = svd_model.test(surprise_test_set)

In [13]:
from surprise import accuracy

rmse = accuracy.rmse(svd_predictions)
mae = accuracy.mae(svd_predictions)
                     
print(rmse, mae)

RMSE: 0.8289
MAE:  0.6474
0.8288711689059135 0.647437483750257

In [15]:
from surprise import NormalPredictor

# инициализируем состояние генератора, это необходимо для получения
# одной и той же последовательности случайных чисел, только в учебных целях
np.random.seed(0)

random_model = NormalPredictor()

random_model.fit(surprise_train_set)
random_predictions = random_model.test(surprise_test_set)

In [16]:
from surprise import accuracy

rmse = accuracy.rmse(random_predictions)
mae = accuracy.mae(random_predictions)
                     
print(rmse, mae)

RMSE: 1.2628
MAE:  1.0018
1.2628030301013033 1.0017726877569562

In [17]:
1.0017726877569562 / 0.647437483750257

1.5472886771309964

In [25]:
# факультативное
events_filtered = events.copy()

In [26]:
events_filtered = events_filtered.merge(events.groupby("item_id").agg(users=("user_id", "nunique")).reset_index(), how="left")

In [28]:
events_filtered = events_filtered[events_filtered["users"] >= 3]

In [29]:
train_test_global_time_split_date = pd.to_datetime("2017-08-01").date()
train_test_global_time_split_idx = events_filtered["started_at"] < train_test_global_time_split_date

events_train_filtered = events_filtered[train_test_global_time_split_idx]
events_test_filtered = events_filtered[~train_test_global_time_split_idx]

In [30]:
reader_filtered = Reader(rating_scale=(1, 5))
surprise_train_set_filtered = Dataset.load_from_df(events_train_filtered[['user_id', 'item_id', 'rating']], reader)
surprise_train_set_filtered = surprise_train_set_filtered.build_full_trainset()

# инициализируем модель
svd_model_filtered = SVD(n_factors=100, random_state=0)

# обучаем модель
svd_model_filtered.fit(surprise_train_set_filtered)

In [35]:
surprise_test_set_filtered = list(events_test_filtered[['user_id', 'item_id', 'rating']].itertuples(index=False))

# получаем рекомендации для тестовой выборки
svd_predictions_filtered = svd_model_filtered.test(surprise_test_set_filtered)

In [34]:
rmse_filtered = accuracy.rmse(svd_predictions_filtered)
mae_filtered = accuracy.mae(svd_predictions_filtered)
                     
print(rmse_filtered, mae_filtered)

RMSE: 0.8288
MAE:  0.6472
0.8287961320807574 0.6472309962190416

In [38]:
def get_recommendations_svd(user_id, all_items, events, model, include_seen=True, n=5):

    """ возвращает n рекомендаций для user_id """
    
    # получим список идентификаторов всех книг
    all_items = set(events['item_id'].unique())
        
    # учитываем флаг, стоит ли уже прочитанные книги включать в рекомендации
    if include_seen:
        items_to_predict = list(all_items)
    else:
        # получим список книг, которые пользователь уже прочитал ("видел")
        seen_items = set(events[events["user_id"] == user_id]['item_id'].unique())
        
        # книги, которые пользователь ещё не читал
        # только их и будем включать в рекомендации
        items_to_predict = list(all_items - seen_items)
    
    # получаем скоры для списка книг, т. е. рекомендации
    predictions = [model.predict(user_id, item_id) for item_id in items_to_predict]
    
    # сортируем рекомендации по убыванию скора и берём только n первых
    recommendations = sorted(predictions, key=lambda x: x.est, reverse=True)[:n]
    
    return pd.DataFrame([(pred.iid, pred.est) for pred in recommendations], columns=["item_id", "score"])

In [42]:
get_recommendations_svd(1296647, items, events_test, svd_model)

    item_id     score
0   7864312  4.981188
1  25793186  4.912001
2  12174312  4.898052
3     13208  4.894869
4  33353628  4.891661

In [43]:
# выберем произвольного пользователя из тренировочной выборки ("прошлого")
user_id = events_train['user_id'].sample().iat[0]

print(f"user_id: {user_id}")

print("История (последние события, recent)")
user_history = (
    events_train
    .query("user_id == @user_id")
    .merge(items.set_index("item_id")[["author", "title", "genre_and_votes"]], on="item_id")
)
user_history_to_print = user_history[["author", "title", "started_at", "read_at", "rating", "genre_and_votes"]].tail(10)
display(user_history_to_print)

print("Рекомендации")
user_recommendations = get_recommendations_svd(user_id, items, events_train, svd_model)
user_recommendations = user_recommendations.merge(items[["item_id", "author", "title", "genre_and_votes"]], on="item_id")
display(user_recommendations)

user_id: 1169023
История (последние события, recent)

,author,title,started_at,read_at,rating,genre_and_votes
68,Veronica Roth,"Divergent (Divergent, #1)",2014-06-02,2014-06-04,4,"{'Young Adult': 20260, 'Science Fiction-Dystop..."
69,"Gillian Flynn, В. Русанов",Gone Girl,2014-05-27,2014-05-29,5,"{'Fiction': 11773, 'Mystery': 9965, 'Thriller'..."
70,Kathy Reichs,"Death du Jour (Temperance Brennan, #2)",2014-05-24,2014-05-27,4,"{'Mystery': 1206, 'Mystery-Crime': 579, 'Ficti..."
71,Chelsea Cain,"Heartsick (Archie Sheridan & Gretchen Lowell, #1)",2014-05-22,2014-05-22,5,"{'Mystery': 832, 'Thriller': 653, 'Fiction': 4..."
72,"Jussi Adler-Olsen, Lisa Hartford","The Keeper of Lost Causes (Department Q, #1)",2014-05-30,2014-06-02,3,"{'Mystery': 1225, 'Mystery-Crime': 627, 'Ficti..."
73,Gillian Flynn,Dark Places,2014-05-17,2014-05-22,4,"{'Mystery': 4534, 'Fiction': 4055, 'Thriller':..."
74,Audrey Niffenegger,Her Fearful Symmetry,2014-05-05,2014-05-08,2,"{'Fiction': 1984, 'Fantasy': 674, 'Fantasy-Par..."
75,Kathy Reichs,"Déjà Dead (Temperance Brennan, #1)",2014-05-13,2014-05-17,4,"{'Mystery': 2141, 'Fiction': 904, 'Mystery-Cri..."
76,Carolyn Parkhurst,The Dogs of Babel,2014-05-09,2014-05-10,5,"{'Fiction': 522, 'Mystery': 102, 'Animals': 77..."
77,George R.R. Martin,"A Dance with Dragons (A Song of Ice and Fire, #5)",2014-05-04,2014-05-04,5,"{'Fantasy': 22247, 'Fiction': 4512, 'Fantasy-E..."

Рекомендации

,item_id,score,author,title,genre_and_votes
0,2199,5,Doris Kearns Goodwin,Team of Rivals: The Political Genius of Abraha...,"{'History': 4174, 'Nonfiction': 2127, 'Biograp..."
1,16255632,5,"David Gaider, Ben Gelinas, Mike Laidlaw, Dave ...",Dragon Age: The World of Thedas Volume 1,"{'Fantasy': 134, 'Games-Video Games': 28, 'Art..."
2,2363958,5,João Guimarães Rosa,Grande Sertão: Veredas,"{'Fiction': 85, 'Classics': 69, 'Cultural-Braz..."
3,22552026,5,Jason Reynolds,Long Way Down,"{'Young Adult': 1871, 'Poetry': 1737, 'Contemp..."
4,29237211,5,"Brian K. Vaughan, Fiona Staples","Saga, Vol. 7 (Saga, #7)","{'Sequential Art-Graphic Novels': 2539, 'Seque..."

# === Базовые подходы: коллаборативная фильтрация

In [5]:
import scipy
import sklearn.preprocessing

# перекодируем идентификаторы пользователей: 
# из имеющихся в последовательность 0, 1, 2, ...
user_encoder = sklearn.preprocessing.LabelEncoder()
user_encoder.fit(events["user_id"])
events_train["user_id_enc"] = user_encoder.transform(events_train["user_id"])
events_test["user_id_enc"] = user_encoder.transform(events_test["user_id"])

# перекодируем идентификаторы объектов: 
# из имеющихся в последовательность 0, 1, 2, ...
item_encoder = sklearn.preprocessing.LabelEncoder()
item_encoder.fit(items["item_id"])
items["item_id_enc"] = item_encoder.transform(items["item_id"])
events_train["item_id_enc"] = item_encoder.transform(events_train["item_id"])
events_test["item_id_enc"] = item_encoder.transform(events_test["item_id"])

/tmp/ipykernel_1893/1044897688.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_train["user_id_enc"] = user_encoder.transform(events_train["user_id"])
/tmp/ipykernel_1893/1044897688.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_test["user_id_enc"] = user_encoder.transform(events_test["user_id"])
/tmp/ipykernel_1893/1044897688.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_train["item_id_enc"] = item_encoder.transform(events_train["item_id"])
/tmp/ipykernel_1893/1044897688.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_test["item_id_enc"] = item_encoder.transform(events_test["item_id"])

In [7]:
events_train["item_id_enc"].max()

43304

In [14]:
events_train["item_id_enc"].max() * events_train["user_id_enc"].max() / (1024 ** 3)

17.365449607372284

In [13]:
events_train["item_id_enc"].nunique() * events_train["user_id_enc"].nunique() / (1024 ** 3)

16.54028546065092

In [15]:
user_item_matrix_train = scipy.sparse.csr_matrix((
    events_train["rating"],
    (events_train['user_id_enc'], events_train['item_id_enc'])),
    dtype=np.int8)

In [16]:
import sys

sum([sys.getsizeof(i) for i in user_item_matrix_train.data])/1024**3

0.26370687410235405

In [17]:
from implicit.als import AlternatingLeastSquares

als_model = AlternatingLeastSquares(factors=50, iterations=50, regularization=0.05, random_state=0)
als_model.fit(user_item_matrix_train)

/home/mle-user/mle_projects/mle-recsys-start/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/mle-user/mle_projects/mle-recsys-start/.venv/lib/python3.10/site-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 4 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()
100%|██████████| 50/50 [02:56<00:00,  3.54s/it]

In [ ]:
def get_recommendations_als(user_item_matrix, model, user_id, user_encoder, item_encoder, include_seen=True, n=5):
    """
    Возвращает отранжированные рекомендации для заданного пользователя
    """
    user_id_enc = user_encoder.transform([user_id])[0]
    recommendations = model.recommend(
         user_id_enc, 
         user_item_matrix[user_id_enc], 
         filter_already_liked_items=not include_seen,
         N=n)
    recommendations = pd.DataFrame({"item_id_enc": recommendations[0], "score": recommendations[1]})
    recommendations["item_id"] = item_encoder.inverse_transform(recommendations["item_id_enc"])
    
    return recommendations

In [20]:
# выберем произвольного пользователя из тренировочной выборки ("прошлого")
user_id = events_train['user_id'].sample().iat[0]

print(f"user_id: {user_id}")

print("История (последние события, recent)")
user_history = (
    events_train
    .query("user_id == @user_id")
    .merge(items.set_index("item_id")[["author", "title", "genre_and_votes"]], on="item_id")
)
user_history_to_print = user_history[["author", "title", "started_at", "read_at", "rating", "genre_and_votes"]].tail(10)
display(user_history_to_print)

print("Рекомендации")
user_recommendations = get_recommendations_als(user_item_matrix_train, als_model, user_id, user_encoder, item_encoder)
user_recommendations = user_recommendations.merge(items[["item_id", "author", "title", "genre_and_votes"]], on="item_id")
display(user_recommendations)

user_id: 1291329
История (последние события, recent)

,author,title,started_at,read_at,rating,genre_and_votes
1,John Grisham,The Client,2015-02-06,2015-02-06,3,"{'Fiction': 2278, 'Mystery': 1058, 'Thriller':..."
2,John Green,Paper Towns,2015-02-04,2015-02-05,5,"{'Young Adult': 9929, 'Contemporary': 3821, 'F..."
3,"Ava Dellaira, Dạ Oanh",Love Letters to the Dead,2015-01-20,2015-01-20,5,"{'Young Adult': 1531, 'Contemporary': 949, 'Fi..."
4,Rainbow Rowell,Fangirl,2015-01-26,2015-01-30,5,"{'Young Adult': 9301, 'Contemporary': 5760, 'R..."
5,Blue Jeans,"No sonrías, que me enamoro (El club de los inc...",2015-01-14,2015-01-16,5,"{'Romance': 37, 'Young Adult': 12, 'Contempora..."
6,Tahereh Mafi,"Destroy Me (Shatter Me, #1.5)",2015-01-10,2015-01-10,5,"{'Young Adult': 1267, 'Science Fiction-Dystopi..."
7,Nicholas Sparks,Dear John,2015-01-10,2015-01-10,5,"{'Romance': 3350, 'Fiction': 1398, 'Womens Fic..."
8,Tahereh Mafi,"Shatter Me (Shatter Me, #1)",2015-01-10,2015-01-10,5,"{'Young Adult': 4770, 'Science Fiction-Dystopi..."
9,Gayle Forman,"Where She Went (If I Stay, #2)",2015-02-25,2015-02-28,5,"{'Young Adult': 4079, 'Romance': 2331, 'Contem..."
10,Gayle Forman,"If I Stay (If I Stay, #1)",2015-02-24,2015-02-25,5,{'Young Adult': 7947}

Рекомендации

,item_id_enc,score,item_id,author,title,genre_and_votes
0,32840,0.804259,15745753,Rainbow Rowell,Eleanor & Park,"{'Young Adult': 11593, 'Romance': 6881, 'Conte..."
1,23978,0.748627,6442769,John Green,Paper Towns,"{'Young Adult': 9929, 'Contemporary': 3821, 'F..."
2,6942,0.731333,99561,John Green,Looking for Alaska,"{'Young Adult': 12128, 'Fiction': 4626, 'Conte..."
3,22228,0.699984,4374400,Gayle Forman,"If I Stay (If I Stay, #1)",{'Young Adult': 7947}
4,33656,0.674619,16068905,Rainbow Rowell,Fangirl,"{'Young Adult': 9301, 'Contemporary': 5760, 'R..."

In [21]:
# получаем список всех возможных user_id (перекодированных)
user_ids_encoded = range(len(user_encoder.classes_))

# получаем рекомендации для всех пользователей
als_recommendations = als_model.recommend(
    user_ids_encoded, 
    user_item_matrix_train[user_ids_encoded], 
    filter_already_liked_items=False, N=100)

In [22]:
# преобразуем полученные рекомендации в табличный формат
item_ids_enc = als_recommendations[0]
als_scores = als_recommendations[1]

als_recommendations = pd.DataFrame({
    "user_id_enc": user_ids_encoded,
    "item_id_enc": item_ids_enc.tolist(), 
    "score": als_scores.tolist()})
als_recommendations = als_recommendations.explode(["item_id_enc", "score"], ignore_index=True)

# приводим типы данных
als_recommendations["item_id_enc"] = als_recommendations["item_id_enc"].astype("int")
als_recommendations["score"] = als_recommendations["score"].astype("float")

# получаем изначальные идентификаторы
als_recommendations["user_id"] = user_encoder.inverse_transform(als_recommendations["user_id_enc"])
als_recommendations["item_id"] = item_encoder.inverse_transform(als_recommendations["item_id_enc"])
als_recommendations = als_recommendations.drop(columns=["user_id_enc", "item_id_enc"])

In [23]:
als_recommendations = als_recommendations[["user_id", "item_id", "score"]]
als_recommendations.to_parquet("als_recommendations.parquet")

In [24]:
als_recommendations = (
    als_recommendations
    .merge(events_test[["user_id", "item_id", "rating"]]
               .rename(columns={"rating": "rating_test"}), 
           on=["user_id", "item_id"], how="left")
)

In [30]:
import sklearn.metrics

def compute_ndcg(rating: pd.Series, score: pd.Series, k):

    """ подсчёт ndcg
    rating: истинные оценки
    score: оценки модели
    k: количество айтемов (по убыванию score) для оценки, остальные - отбрасываются
    """
    
    # если кол-во объектов меньше 2, то NDCG - не определена
    if len(rating) < 2:
        return np.nan

    ndcg = sklearn.metrics.ndcg_score(np.asarray([rating.to_numpy()]), np.asarray([score.to_numpy()]), k=k)

    return ndcg

In [31]:
rating_test_idx = ~als_recommendations["rating_test"].isnull()
ndcg_at_5_scores = als_recommendations[rating_test_idx].groupby("user_id").apply(lambda x: compute_ndcg(x["rating_test"], x["score"], k=5))

In [34]:
print(ndcg_at_5_scores.mean())

0.975946709792109

In [37]:
ndcg_at_5_scores.isna().sum() / len(ndcg_at_5_scores)

0.641923756102628

In [38]:
def get_similar_items_als(model, item_id, item_encoder, n=5):
    """
    Возвращает похожие книги
    """
    item_id_enc = item_encoder.transform([item_id])[0]
    recommendations = model.similar_items(
         item_id_enc,
         N=n)
    recommendations = pd.DataFrame({"item_id_enc": recommendations[0], "score": recommendations[1]})
    recommendations["item_id"] = item_encoder.inverse_transform(recommendations["item_id_enc"])
    
    return recommendations

In [39]:
# выберем произвольную книгу из тренировочной выборки ("прошлого")
item_id = events_train['item_id'].sample().iat[0]

print(f"item_id: {item_id}")

display(items[items["item_id"] == item_id])

print("Рекомендации")
user_recommendations = get_similar_items_als(als_model, item_id, item_encoder)
user_recommendations = user_recommendations.merge(items[["item_id", "author", "title", "genre_and_votes"]], on="item_id")
display(user_recommendations)

item_id: 24920901

,item_id,author,title,description,genre_and_votes,num_pages,average_rating,ratings_count,text_reviews_count,publisher,publication_year,country_code,language_code,format,is_ebook,isbn,isbn13,genre_and_votes_dict,genre_and_votes_str,item_id_enc
1713099,24920901,Elle Kennedy,"The Deal (Off-Campus, #1)",She's about to make a deal with the college ba...,"{'Romance': 3185, 'New Adult': 2715, 'Contempo...",342,4.3,79120,6697,Elle Kennedy Inc.,2008,US,eng,Paperback,True,,,"{'Academic': None, 'Academic-Academia': None, ...","Romance 3185, New Adult 2715, Contemporary 121...",40300

Рекомендации

,item_id_enc,score,item_id,author,title,genre_and_votes
0,40300,1.000000,24920901,Elle Kennedy,"The Deal (Off-Campus, #1)","{'Romance': 3185, 'New Adult': 2715, 'Contempo..."
1,40712,0.985769,25564665,Elle Kennedy,"The Mistake (Off-Campus, #2)","{'Romance': 1744, 'New Adult': 1737, 'Sports-S..."
2,41369,0.974826,27252717,Elle Kennedy,"The Score (Off-Campus, #3)","{'Romance': 1505, 'New Adult': 1404, 'Sports-S..."
3,37947,0.951969,20803953,Penelope Douglas,"Bully (Fall Away, #1)","{'Romance': 1790, 'New Adult': 1438, 'Contempo..."
4,42067,0.943245,29991719,Emma Chase,"Royally Screwed (Royally, #1)","{'Romance': 1310, 'Contemporary': 505, 'New Ad..."

# === Базовые подходы: контентные рекомендации

In [41]:
items["genre_and_votes"] = items["genre_and_votes"].apply(eval)

In [45]:
def get_genres(items):

    """ 
    извлекает список жанров по всем книгам, 
    подсчитывает долю голосов по каждому их них
    """
    
    genres_counter = {}
    
    for k, v, in items.iterrows():
        genre_and_votes = v["genre_and_votes"]
        if genre_and_votes is None or not isinstance(genre_and_votes, dict):
            continue
        for genre, votes in genre_and_votes.items():
            # увеличиваем счётчик жанров
            try:
                genres_counter[genre] += votes
            except KeyError:
                genres_counter[genre] = votes

    genres = pd.Series(genres_counter, name="votes")
    genres = genres.to_frame()
    genres = genres.reset_index().rename(columns={"index": "name"})
    genres.index.name = "genre_id"
    
    return genres
   
genres = get_genres(items)

In [46]:
genres

                                    name    votes
genre_id
0               Womens Fiction-Chick Lit   255297
1                                Fiction  6406698
2                               Politics   103297
3                                  Humor   304303
4                              Christian   105668
...                                  ...      ...
810            German History-Nazi Party        3
811                            Favorites        3
812       History-Latin American History        2
813                     Cryptids-Bigfoot        1
814                   Politics-Far Right        4

[815 rows x 2 columns]

In [47]:
genres["score"] = genres["votes"] / genres["votes"].sum()
genres.sort_values(by="score", ascending=False).head(10)

                                   name    votes     score
genre_id
25                              Fantasy  6850115  0.149498
1                               Fiction  6406698  0.139821
38                             Classics  3415071  0.074531
18                          Young Adult  3297027  0.071955
34                              Romance  2422690  0.052873
5                            Nonfiction  1737798  0.037926
16        Historical-Historical Fiction  1531489  0.033423
20                              Mystery  1371370  0.029929
24                      Science Fiction  1218997  0.026604
33                   Fantasy-Paranormal   857137  0.018706

In [48]:
def get_item2genre_matrix(genres, items):

    genre_names_to_id = genres.reset_index().set_index("name")["genre_id"].to_dict()
    
    # list to build CSR matrix
    genres_csr_data = []
    genres_csr_row_idx = []
    genres_csr_col_idx = []
    
    for item_idx, (k, v) in enumerate(items.iterrows()):
        if v["genre_and_votes"] is None:
            continue
        for genre_name, votes in v["genre_and_votes"].items():
            genre_idx = genre_names_to_id[genre_name]
            genres_csr_data.append(int(votes))
            genres_csr_row_idx.append(item_idx)
            genres_csr_col_idx.append(genre_idx)

    genres_csr = scipy.sparse.csr_matrix((genres_csr_data, (genres_csr_row_idx, genres_csr_col_idx)), shape=(len(items), len(genres)))
    # нормализуем, чтобы сумма оценок принадлежности к жанру была равна 1
    genres_csr = sklearn.preprocessing.normalize(genres_csr, norm='l1', axis=1)
    
    return genres_csr

In [52]:
items = items.sort_values(by="item_id_enc")
all_items_genres_csr = get_item2genre_matrix(genres, items)

In [53]:
all_items_genres_csr

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 210895 stored elements and shape (43312, 815)>

In [54]:
user_id = 1000010
user_events = events_train.query("user_id == @user_id")[["item_id", "rating"]]
user_items = items[items["item_id"].isin(user_events["item_id"])]

user_items_genres_csr = get_item2genre_matrix(genres, user_items)
user_items_genres_csr

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 149 stored elements and shape (22, 815)>

In [55]:
# вычислим склонность пользователя к жанрам как среднее взвешенное значение популяции на его оценки книг.

# преобразуем пользовательские оценки из списка в вектор-столбец
user_ratings = user_events["rating"].to_numpy() / 5
user_ratings = np.expand_dims(user_ratings, axis=1)

user_items_genres_weighted = user_items_genres_csr.multiply(user_ratings)

user_genres_scores = np.asarray(user_items_genres_weighted.mean(axis=0))

In [61]:
# выведем список жанров, которые предпочитает пользователь

user_genres = genres.copy()
user_genres["score"] = np.ravel(user_genres_scores)
user_genres = user_genres[user_genres["score"] > 0].sort_values(by=["score"], ascending=False)

user_genres.head(5)

                     name    votes     score
genre_id
1                 Fiction  6406698  0.185241
38               Classics  3415071  0.103879
25                Fantasy  6850115  0.072447
5              Nonfiction  1737798  0.050865
24        Science Fiction  1218997  0.040920

In [94]:
from sklearn.metrics.pairwise import cosine_similarity

# вычисляем сходство между вектором пользователя и векторами по книгам
similarity_scores = cosine_similarity(all_items_genres_csr, user_genres_scores)

# преобразуем в одномерный массив
similarity_scores = similarity_scores.flatten()

# получаем индексы top-k (по убыванию значений), по сути, индексы книг (encoded)
k = 5
top_k_indices = pd.DataFrame({"item_id_enc": items["item_id_enc"], "score": similarity_scores}).sort_values(by='score', ascending=False)["item_id_enc"][:5].to_numpy().tolist()

In [95]:
selected_items = items[items["item_id_enc"].isin(top_k_indices)]

with pd.option_context("max_colwidth", 100):
   display(selected_items[["author", "title", "genre_and_votes"]])

,author,title,genre_and_votes
80465,G.K. Chesterton,The Napoleon of Notting Hill,"{'Fiction': 166, 'Classics': 88, 'Fantasy': 44, 'Humor': 22, 'Literature': 20}"
1168335,Ray Bradbury,"Dandelion Wine (Green Town, #1)","{'Fiction': 1438, 'Classics': 914, 'Science Fiction': 529, 'Fantasy': 456, 'Young Adult': 212}"
393210,"G.K. Chesterton, Jonathan Lethem",The Man Who Was Thursday: A Nightmare,"{'Fiction': 1257, 'Classics': 929, 'Mystery': 469, 'Fantasy': 293, 'Philosophy': 156, 'Literatur..."
2244467,Samuel Butler,"Erewhon (Erewhon , #1)","{'Fiction': 162, 'Classics': 139, 'Science Fiction': 60, 'Fantasy': 55}"
39408,"Paulo Coelho, Alan R. Clarke, James Noel Smith",The Alchemist,"{'Fiction': 14023, 'Classics': 5787, 'Fantasy': 3289, 'Philosophy': 2759}"

# === Базовые подходы: валидация

In [96]:
def process_events_recs_for_binary_metrics(events_train, events_test, recs, top_k=None):

    """
    размечает пары <user_id, item_id> для общего множества пользователей признаками
    - gt (ground truth)
    - pr (prediction)
    top_k: расчёт ведётся только для top k-рекомендаций
    """

    events_test["gt"] = True
    common_users = set(events_test["user_id"]) & set(recs["user_id"])

    print(f"Common users: {len(common_users)}")
    
    events_for_common_users = events_test[events_test["user_id"].isin(common_users)].copy()
    recs_for_common_users = recs[recs["user_id"].isin(common_users)].copy()

    recs_for_common_users = recs_for_common_users.sort_values(["user_id", "score"], ascending=[True, False])

    # оставляет только те item_id, которые были в events_train, 
    # т. к. модель не имела никакой возможности давать рекомендации для новых айтемов
    events_for_common_users = events_for_common_users[events_for_common_users["item_id"].isin(events_train["item_id"].unique())]

    if top_k is not None:
        recs_for_common_users = recs_for_common_users.groupby("user_id").head(top_k)
    
    events_recs_common = events_for_common_users[["user_id", "item_id", "gt"]].merge(
        recs_for_common_users[["user_id", "item_id", "score"]], 
        on=["user_id", "item_id"], how="outer")    

    events_recs_common["gt"] = events_recs_common["gt"].fillna(False)
    events_recs_common["pr"] = ~events_recs_common["score"].isnull()
    
    events_recs_common["tp"] = events_recs_common["gt"] & events_recs_common["pr"]
    events_recs_common["fp"] = ~events_recs_common["gt"] & events_recs_common["pr"]
    events_recs_common["fn"] = events_recs_common["gt"] & ~events_recs_common["pr"]

    return events_recs_common

In [ ]:
events_recs_for_binary_metrics = process_events_recs_for_binary_metrics(
    events_train,
    events_test, 
    als_recommendations, 
    top_k=5
)

/tmp/ipykernel_1893/3166051426.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_test["gt"] = True

Common users: 123223

In [98]:
events_recs_for_binary_metrics

         user_id   item_id     gt     score     pr     tp     fp     fn
0        1196635  18467802   True       NaN  False  False  False   True
1        1188739     10799   True       NaN  False  False  False   True
2        1001879  13206828   True       NaN  False  False  False   True
3        1001879  13206900   True       NaN  False  False  False   True
4        1001879  13206760   True       NaN  False  False  False   True
...          ...       ...    ...       ...    ...    ...    ...    ...
1030163  1430584  29056083  False  0.472945   True  False   True  False
1030164  1430584  17167166  False  0.463936   True  False   True  False
1030165  1430584  17927395  False  0.460429   True  False   True  False
1030166  1430584  16096824  False  0.454709   True  False   True  False
1030167  1430584  20613470  False  0.445634   True  False   True  False

[1030168 rows x 8 columns]

In [99]:
def compute_cls_metrics(events_recs_for_binary_metric):
    
    groupper = events_recs_for_binary_metric.groupby("user_id")

    # precision = tp / (tp + fp)
    precision = groupper["tp"].sum()/(groupper["tp"].sum()+groupper["fp"].sum())
    precision = precision.fillna(0).mean()
    
    # recall = tp / (tp + fn)
    recall = groupper["tp"].sum()/(groupper["tp"].sum()+groupper["fn"].sum())
    recall = recall.fillna(0).mean()

    return precision, recall

In [100]:
compute_cls_metrics(events_recs_for_binary_metrics)

(0.007581376853347184, 0.014121568795222568)

In [101]:
events_recs_for_binary_metrics_10 = process_events_recs_for_binary_metrics(
    events_train,
    events_test, 
    als_recommendations, 
    top_k=10
)

/tmp/ipykernel_1893/3166051426.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_test["gt"] = True

Common users: 123223

In [102]:
compute_cls_metrics(events_recs_for_binary_metrics_10)

(0.008732947582837622, 0.03130238527136974)

# === Двухстадийный подход: метрики

# === Двухстадийный подход: модель

# === Двухстадийный подход: построение признаков